CREATE TABLE IF NOT EXISTS `ai_device_live_event_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `source` varchar(64) NOT NULL DEFAULT '' COMMENT '上报来源',
  `record_id` varchar(128) NOT NULL DEFAULT '' COMMENT '中控事件唯一标识',
  `room_id` varchar(128) NOT NULL DEFAULT '' COMMENT '直播间ID',
  `room_title` varchar(255) NOT NULL DEFAULT '' COMMENT '直播间标题',
  `event_type` varchar(64) NOT NULL DEFAULT '' COMMENT '事件类型',
  `priority` varchar(16) NOT NULL DEFAULT '' COMMENT '优先级',
  `actor_id` varchar(128) NOT NULL DEFAULT '' COMMENT '人物ID',
  `actor_name` varchar(255) NOT NULL DEFAULT '' COMMENT '人物名称',
  `content` text COMMENT '事件内容',
  `live_heat` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '热度值',
  `normalized_payload` longtext COMMENT '标准化负载JSON',
  `raw_payload` longtext COMMENT '原始负载JSON',
  `event_created_at` datetime DEFAULT NULL COMMENT '事件发生时间',
  `reported_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上报时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_live_event_record` (`source`,`record_id`),
  KEY `idx_live_event_room_id` (`room_id`),
  KEY `idx_live_event_type` (`event_type`),
  KEY `idx_live_event_created_at` (`event_created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='直播中控事件记录';

CREATE TABLE IF NOT EXISTS `ai_device_live_command_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `source` varchar(64) NOT NULL DEFAULT '' COMMENT '上报来源',
  `record_id` varchar(128) NOT NULL DEFAULT '' COMMENT '中控命令唯一标识',
  `room_id` varchar(128) NOT NULL DEFAULT '' COMMENT '直播间ID',
  `room_title` varchar(255) NOT NULL DEFAULT '' COMMENT '直播间标题',
  `command_type` varchar(64) NOT NULL DEFAULT '' COMMENT '命令类型',
  `priority_track` varchar(16) NOT NULL DEFAULT '' COMMENT '命令轨道',
  `status` varchar(32) NOT NULL DEFAULT '' COMMENT '命令状态',
  `target_device` varchar(255) NOT NULL DEFAULT '' COMMENT '目标设备或对象',
  `error_message` text COMMENT '错误信息',
  `payload` longtext COMMENT '命令负载JSON',
  `command_created_at` datetime DEFAULT NULL COMMENT '命令创建时间',
  `dispatched_at` datetime DEFAULT NULL COMMENT '命令下发时间',
  `reported_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上报时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_live_command_record` (`source`,`record_id`),
  KEY `idx_live_command_room_id` (`room_id`),
  KEY `idx_live_command_type` (`command_type`),
  KEY `idx_live_command_created_at` (`command_created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='直播中控命令记录';